<a href="https://colab.research.google.com/github/PJibin/test_poject/blob/main/lesson_01_contents_orientation_%26_numpy_1_array%2C_zero%2C_one.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 목차
    - numpy
    - pandas
    - matplotlib & seaborn
    - scikit-learn

### Numpy
    - 행렬 연산을 가능하게 해주는 패키지
    - python으로 작성되나 연산은 C, C++, 포트란으로 진행
        - 선형대수 연산을 빠르게 할 수 있음

In [1]:
import numpy as np #넘파이 라이브러리 불러오기. 및 np작성시 넘파이 사용약속
ary = np.array([1, 2, 3],dtype='int32')
type(ary), ary

(numpy.ndarray, array([1, 2, 3], dtype=int32))

    - ndarray : 한가지 데이터 타입만으로 사용이 가능

In [2]:
ary2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(ary2)   ##행렬 확인
print(ary2.ndim) ##행렬의 차원
print(ary2.shape) ##행렬의 형태
print(ary2.size)  ## 행렬 내 원소 개수
print(ary2.dtype)  ##행렬의 자료형

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64


In [3]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

In [4]:
a=np.random.randint(2,10,size=(5,))
b=np.random.randint(2,10,size=(2,4))
c=np.random.randint(2,10,size=(2,3,4))
print(a)
print(b)
print(c)

[7 9 5 5 3]
[[4 5 8 6]
 [4 4 4 7]]
[[[2 9 4 7]
  [4 8 5 4]
  [3 5 5 8]]

 [[8 6 7 7]
  [7 9 4 4]
  [3 5 5 3]]]


In [5]:
ary2.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
ary2[1]

array([4, 5, 6])

In [ ]:
ary2[1, 1]

5

#### 데이터 수정

In [ ]:
ls = [1, 2, 3]
ls[1] = 5
ls

[1, 5, 3]

In [9]:
ary3 = np.array([[1, 2, 3],
                 [0, 1, 0]])
ary3[1][1] = 0
ary3

array([[1, 2, 3],
       [0, 0, 0]])

##### array 브로드캐스팅

In [10]:
ary3[0] = 0
ary3

array([[0, 0, 0],
       [0, 0, 0]])

##### array 조건 선택

In [11]:
ary3[0] = 5
ary3[1] = [5, 6, 7]
ary3

array([[5, 5, 5],
       [5, 6, 7]])

In [12]:
idx = ary3>5
idx

array([[False, False, False],
       [False,  True,  True]])

In [13]:
ary3[idx]

array([6, 7])

##### 조건에 맞는 값만 변경

In [14]:
ary3[idx] = 100
ary3

array([[  5,   5,   5],
       [  5, 100, 100]])

#### zero array

In [15]:
zero_ary = np.zeros((2, 3))
zero_ary

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
type(zero_ary)

numpy.ndarray

In [17]:
zero_ary.dtype # 실수형 값만 바꿔 넣을 수 있음

dtype('float64')

##### array안의 데이터 형태 변경

In [ ]:
z2 = zero_ary.astype('int')
z2.dtype

dtype('int32')

#### one array

In [ ]:
one_ary = np.ones((2, 3))
one_ary.dtype, one_ary

(dtype('float64'),
 array([[1., 1., 1.],
        [1., 1., 1.]]))

In [ ]:
one_ary2 = np.ones((2, 3, 2)).astype('int')
one_ary2.dtype, one_ary2

(dtype('int32'),
 array([[[1, 1],
         [1, 1],
         [1, 1]],
 
        [[1, 1],
         [1, 1],
         [1, 1]]]))

#### 범위값 array 생성

In [ ]:
arg = np.arange(1, 11)
arg

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])